AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API functions for MR Optimum

Parameters:
  Environment:
    Type: String
    Default: dev

  SequencesBucketName:
    Type: String

  StateMachineArn:
    Type: String

Resources:
  ProcessSequenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "process-sequence-${Environment}"
      CodeUri: ./src/user-authorizer-python/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          SEQUENCES_BUCKET: !Ref SequencesBucketName
          STATE_MACHINE_ARN: !Ref StateMachineArn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref StateMachineArn
      Events:
        Api:
          Type: HttpApi