version = 0.1

[default.deploy]
stack_name = "MRORootStack"
s3_bucket = "mro-deploy-bucket-agrima"
s3_prefix = "mro"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
template_file = "cloudformation/root.yaml"

