AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ark function to handle failed results and job updates

Parameters:
  Environment:
    Type: String
    Default: dev

  FailedBucketName:
    Type: String

  UpdateJobFunctionArn:
    Type: String

Resources:
  ArkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ark-handler-${Environment}"
      CodeUri: ../src/configure-bucket-notification/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          FAILED_BUCKET: !Ref FailedBucketName
          UPDATE_JOB_ARN: !Ref UpdateJobFunctionArn
          ENVIRONMENT: !Ref Environment
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Ref UpdateJobFunctionArn
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${FailedBucketName}/*"
      FunctionUrlConfig:
        AuthType: NONE

  ApiTokenGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build/ark/api_token_generator/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mro/api-token
      Environment:
        Variables:
          PARAMETER_NAME: "/mro/api-token"

Outputs:
  ApiToken:
    Description: "The API token for Amplify environment variables"
    Value: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mro/api-token
    Export:
      Name: !Sub "ApiToken-${AWS::StackName}"


