AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Common stack with shared S3 buckets and APIs for MR Optimum

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mro-results-${Environment}-${AWS::Region}"

  FailedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mro-failed-${Environment}-${AWS::Region}"

  PipelineCompletedApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "pipeline-completed-api-${Environment}"

  PipelineFailedApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "pipeline-failed-api-${Environment}"

  PipelineSchedulerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "pipeline-scheduler-api-${Environment}"

Outputs:
  ResultsBucket:
    Description: S3 bucket for successful results
    Value: !Ref ResultsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ResultsBucket"

  FailedBucket:
    Description: S3 bucket for failed jobs
    Value: !Ref FailedBucket
    Export:
      Name: !Sub "${AWS::StackName}-FailedBucket"

  PipelineCompletedApi:
    Description: API endpoint for completed pipelines
    Value: !Sub "${PipelineCompletedApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-PipelineCompletedApi"

  PipelineFailedApi:
    Description: API endpoint for failed pipelines
    Value: !Sub "${PipelineFailedApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-PipelineFailedApi"

  PipelineSchedulerApi:
    Description: API endpoint for scheduling pipelines
    Value: !Sub "https://${PipelineSchedulerApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-PipelineSchedulerApi"

  Host:
    Description: Hostname for API calls
    Value: !Sub "${PipelineCompletedApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-Host"
