AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Common resources - buckets, shared APIs, and host for MR Optimum

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  SequencesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mro-sequences-${Environment}-${AWS::Region}"

  FieldsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mro-fields-${Environment}-${AWS::Region}"

  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mro-results-${Environment}-${AWS::Region}"

  FailedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mro-failed-${Environment}-${AWS::Region}"

  PipelineCompletedApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "pipeline-completed-api-${Environment}"

  PipelineFailedApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "pipeline-failed-api-${Environment}"

  PipelineSchedulerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "pipeline-scheduler-api-${Environment}"

Outputs:
  SequencesBucket:
    Value: !Ref SequencesBucket
    Export:
      Name: CommonStack-SequencesBucket

  FieldsBucket:
    Value: !Ref FieldsBucket
    Export:
      Name: CommonStack-FieldsBucket

  ResultsBucket:
    Value: !Ref ResultsBucket
    Export:
      Name: CommonStack-ResultsBucket

  FailedBucket:
    Value: !Ref FailedBucket
    Export:
      Name: CommonStack-FailedBucket

  PipelineCompletedApi:
    Value: !Sub "${PipelineCompletedApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: CommonStack-PipelineCompletedApi

  PipelineFailedApi:
    Value: !Sub "${PipelineFailedApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: CommonStack-PipelineFailedApi

  PipelineSchedulerApi:
    Value: !Sub "${PipelineSchedulerApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: CommonStack-PipelineSchedulerApi

  Host:
    Value: !Sub "${PipelineCompletedApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: CommonStack-Host
