AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Compute functions for MR Optimum backend

Parameters:
  Environment:
    Type: String
    Default: dev
  PipelineCompleted:
    Type: String
  PipelineFailed:
    Type: String
  PipelineScheduler:
    Type: String
  ResultsBucketName:
    Type: String
  FailedBucketName:
    Type: String
  Host:
    Type: String

Resources:

  RunJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/run-job-python/
      Handler: app.handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          ECR_IMAGE_URI: 879381258545.dkr.ecr.us-east-1.amazonaws.com/mr-optimum-job:latest
          CLUSTER_NAME: !Sub "mr-optimum-cluster-${Environment}"
          TASK_DEF: !Sub "mr-optimum-task-${Environment}"
          SUBNET_ID: subnet-086697b339ea637c6  # Replace with real
          SECURITY_GROUP_ID: sg-067975bcba7308272 # Replace with real
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
                - iam:PassRole
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${FailedBucketName}/*"

  UpdateJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/update-job-python/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          PipelineCompleted: !Ref PipelineCompleted
          PipelineFailed: !Ref PipelineFailed
          PipelineScheduler: !Ref PipelineScheduler
          ResultsBucketName: !Ref ResultsBucketName
          FailedBucketName: !Ref FailedBucketName
          Host: !Ref Host
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub arn:aws:s3:::${ResultsBucketName}/*
                - !Sub arn:aws:s3:::${FailedBucketName}/*

Outputs:
  RunJobFunctionFargateArn:
    Description: ARN of the RunJob Lambda function (Fargate-style call)
    Value: !GetAtt RunJobFunction.Arn
    Export:
      Name: ComputeStack-RunJobFunctionFargateArn

  RunJobFunctionArn:
    Description: ARN of the RunJob Lambda function
    Value: !GetAtt RunJobFunction.Arn
    Export:
      Name: ComputeStack-RunJobFunctionArn

  UpdateJobFunctionArn:
    Description: ARN of the UpdateJob Lambda function
    Value: !GetAtt UpdateJobFunction.Arn
    Export:
      Name: ComputeStack-UpdateJobFunctionArn
