AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Compute functions for MR Optimum backend

Parameters:
  Environment:
    Type: String
    Default: dev
  PipelineCompleted:
    Type: String
  PipelineFailed:
    Type: String
  PipelineScheduler:
    Type: String
  ResultsBucketName:
    Type: String
  FailedBucketName:
    Type: String
  Host:
    Type: String

Resources:
  RunJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:  ../src/run-job-python/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 3008
      PackageType: Zip
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: NONE

  UpdateJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:  ../src/update-job-python/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          PipelineCompleted: !Ref PipelineCompleted
          PipelineFailed: !Ref PipelineFailed
          PipelineScheduler: !Ref PipelineScheduler
          ResultsBucketName: !Ref ResultsBucketName
          FailedBucketName: !Ref FailedBucketName
          Host: !Ref Host
      Policies:
        - AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  RunJobFunctionArn:
    Description: ARN of the RunJob Lambda function
    Value: !GetAtt RunJobFunction.Arn
    Export:
      Name: ComputeStack-RunJobFunctionArn

  UpdateJobFunctionArn:
    Description: ARN of the UpdateJob Lambda function
    Value: !GetAtt UpdateJobFunction.Arn
    Export:
      Name: ComputeStack-UpdateJobFunctionArn
