AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Frontend Lambda to trigger updates or inspect failed results from UI

Parameters:
  Environment:
    Type: String
    Default: dev

  FailedBucketName:
    Type: String

  UpdateJobFunctionArn:
    Type: String

Resources:
  FrontendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "frontend-handler-${Environment}"
      CodeUri: ../src/notify/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          FAILED_BUCKET: !Ref FailedBucketName
          UPDATE_JOB_ARN: !Ref UpdateJobFunctionArn
          ENVIRONMENT: !Ref Environment
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Ref UpdateJobFunctionArn
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${FailedBucketName}/*"
      FunctionUrlConfig:
        AuthType: NONE
