AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MR Optimum Modular Root Stack using AWS::Serverless::Application

Parameters:
  Environment:
    Type: String
    Default: dev
  GithubToken:
    Type: String
    Description: GitHub token for Amplify to connect to the repo
  # CloudmrServer:
  #   Type: String
  #   Description: URL for CloudMR server
  # MroServer:
  #   Type: String
  #   Description: URL for MRO server
  # ProfileServer:
  #   Type: String
  #   Description: URL for profile server
  # ApiUrl:
  #   Type: String
  #   Description: Base URL for backend API (e.g., API Gateway)
  # ApiToken:
  #   Type: String
  #   Description: API access token

  
Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Runtime: python3.9
    Architectures: [x86_64]

Resources:

  CommonStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: common.yaml
      Parameters:
        Environment: !Ref Environment

  ComputeStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: compute.yaml
      Parameters:
        Environment: !Ref Environment
        PipelineCompleted: !GetAtt CommonStack.Outputs.PipelineCompletedApi
        PipelineFailed: !GetAtt CommonStack.Outputs.PipelineFailedApi
        PipelineScheduler: !GetAtt CommonStack.Outputs.PipelineSchedulerApi
        Host: !GetAtt CommonStack.Outputs.Host
        ResultsBucketName: !Sub "mro-results-${Environment}-${AWS::Region}"
        FailedBucketName: !Sub "mro-failed-${Environment}-${AWS::Region}"

  StepFunctionStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stepfunction.yaml
      Parameters:
        Environment: !Ref Environment
        RunJobFunctionArn: !GetAtt ComputeStack.Outputs.RunJobFunctionArn
        UpdateJobFunctionArn: !GetAtt ComputeStack.Outputs.UpdateJobFunctionArn
        RunJobFunctionFargateArn: !GetAtt ComputeStack.Outputs.RunJobFunctionFargateArn  

  APIStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../api.yaml
      Parameters:
        Environment: !Ref Environment
        SequencesBucketName: !Sub "mro-results-${Environment}-${AWS::Region}"
        StateMachineArn: !GetAtt StepFunctionStack.Outputs.StateMachineArn
        PipelineScheduler: !GetAtt CommonStack.Outputs.PipelineSchedulerApi
        Host: !GetAtt CommonStack.Outputs.Host
        DataBucketName: !GetAtt CommonStack.Outputs.DataBucketName

  ArkStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ark.yaml
      Parameters:
        Environment: !Ref Environment
        FailedBucketName: !Sub "mro-failed-${Environment}-${AWS::Region}"
        UpdateJobFunctionArn: !GetAtt ComputeStack.Outputs.UpdateJobFunctionArn

  FrontendStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: frontend.yaml
      Parameters:
        Environment: !Ref Environment
        FailedBucketName: !Sub "mro-failed-${Environment}-${AWS::Region}"
        UpdateJobFunctionArn: !GetAtt ComputeStack.Outputs.UpdateJobFunctionArn


  AmplifyStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: amplify.yaml
      Parameters:
        GithubToken: !Ref GithubToken
        CloudmrServer: !GetAtt CommonStack.Outputs.Host
        MroServer: !GetAtt APIStack.Outputs.MROApi
        ProfileServer: !GetAtt CommonStack.Outputs.ProfileGetAPI
        ApiUrl: !GetAtt APIStack.Outputs.QueueJobApi
        ApiToken: !GetAtt ArkStack.Outputs.ApiToken


  FargateStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: fargate.yaml
      Parameters:
        Environment: !Ref Environment
        ContainerImage: "879381258545.dkr.ecr.us-east-1.amazonaws.com/mr-optimum-fargate"
        SubnetID: "subnet-086697b339ea637c6"
        SecurityGroupID: "sg-067975bcba7308272"
        RunJobFunctionArn: !GetAtt ComputeStack.Outputs.RunJobFunctionArn
        UpdateJobFunctionArn: !GetAtt ComputeStack.Outputs.UpdateJobFunctionArn
        ResultsBucketName: !Sub "mro-results-${Environment}-${AWS::Region}"
        FailedBucketName: !Sub "mro-failed-${Environment}-${AWS::Region}"






